### PR TITLE
Update diffusers to HF's repo

### PR DESCRIPTION
**Pull request by orangetin**
Fixes several bugs with new image models by replacing an outdated fork with the latest upstream repo

### CODE REVIEW

**Review by justin-together — APPROVED** [review]
It would be great to time a few image generations pre and post patch.

**Comment by orangetin** [comment]
Agreed! Go for it and let me know / merge when done

**Comment by csris** [comment]
@orangetin you now have merge access here, too.

**Comment by orangetin** [comment]
Thanks. I'm waiting for @justin-together  to benchmark the current image generation as per his comment earlier

**Pull request merged**
